name: Daily MGDD Weather Sync

on:
  schedule:
    # This is a Cron syntax that triggers the script every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows you to manually click a button in GitHub to run it anytime

jobs:
  build-and-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Weather Data Collection Script
        run: node scripts/weather-sync.js

      - name: Commit and Push Updated Weather Data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git add nn/scripts/weather-cache.json
          git diff-index --quiet HEAD || git commit -m "Automated night-sync: Updated local MGDD values"
          git push
